# Generated by Django 3.1.6 on 2021-02-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
